###############################################################################
############################ MongoDB ##########################################
###############################################################################


###############################################################################
## Common image variables
###############################################################################
## Architecture - e.g. amd64, s390x, ppc64le. Specific worker node architecture
## to deploy to.
## You can use kubectl version command to determine the architecture on the
## desired worker node.

# Specify architecture (amd64, ppc64le, s390x) and weight to be  used for scheduling as follows :
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

image: 
  repository: "ibmcom/mongodb" 
  tag: "3.6.0"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
  imagePullPolicy: IfNotPresent


###############################################################################
## Persistence Storage
###############################################################################

## Persistence enabled by default
## global persistence settings
persistence:
  enabled: true
  useDynamicProvisioning: false

dataVolume:
  name: "datavolume"

  ## Specify the name of the Existing Claim to be used by your application
  existingClaimName: ""
 
  ## Specify the name of the StorageClass
  ## empty string means don't use a StorageClass
  storageClassName: ""

  ## Required minimum Persistence Storage volume size of 8Gi
  size: 20Gi

## sub-path inside the referenced volume instead of its root if specified
volumeMounts:
  data:
    subPath: ""

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    cpu: 2
    memory: 4Gi

service:
  name: ibm-mongodb-dev
  type: NodePort
  port: 27017


## Database access attributes - empty value will be
## overriden with default
database :
  user: "mongo"
  password: ""
  name: "admin"
  dbcmd: "mongo"

  ## Specify initial db arguments defined by image , e.g. --data-checksums
  ## ref: <database specific documentation regarding initialization parameters>
  # initdbArgs: ""

